config:
  features:
    ALLOW_PRIVATE_IPS:
      isEnabled: false
    GZIP:
      isEnabled: true
    JWT_CHECK_CONFIG:
      isEnabled: false
      config:
        issuer: https://apskyxzcl.accounts400.ondemand.com
        jwksUri: https://apskyxzcl.accounts400.ondemand.com/oauth2/certs
        clientId: d0316c58-b0fe-45cd-9960-0fea0708355a
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.dev.kyma.cloud.sap'
        tokenUrl: 'https://kymatest.accounts400.ondemand.com/oauth2/token'
        issuerUrl: 'https://kymatest.accounts400.ondemand.com'
