config:
  storage: localStorage
  features:
    PROTECTED_RESOURCES:
      isEnabled: true
      config:
        resources:
          - match:
              $.metadata.labels['serverless.kyma-project.io/managed-by']: function-controller
            message: 'Resource managed by: function-controller'
          - match:
              $.metadata.labels['reconciler.kyma-project.io/managed-by']: reconciler
            messageSrc: >-
              $.metadata.annotations['reconciler.kyma-project.io/managed-by-reconciler-disclaimer']
          - match:
              $.metadata.labels['istio.io/rev']: default
            message: Resource managed by Istio control plane
          - match:
              $.metadata.labels['applicationconnector.kyma-project.io/managed-by']: compass-runtime-agent
    LEGAL_LINKS:
      config:
        legal-disclosure:
          default: https://www.sap.com/corporate/en/legal/impressum.html
          de: https://www.sap.com/corporate/de/legal/impressum.html
        privacy:
          default: >-
            https://help.sap.com/viewer/82bdf2271c6041f79387c122147cf774/Cloud/en-US
        copyright:
          default: https://www.sap.com/corporate/en/legal/copyright.html
          de: https://www.sap.com/corporate/de/legal/copyright.html
        trademark:
          default: https://www.sap.com/corporate/en/legal/trademark.html
          de: https://www.sap.com/corporate/de/legal/trademark.html
    KUBECONFIG_ID:
      isEnabled: true
      config:
        kubeconfigUrl: https://kyma-env-broker.cp.dev.kyma.cloud.sap/kubeconfig
    SENTRY:
      isEnabled: true
      config:
        dsn: https://016845744e4741cc9bea0caaabc0fe87@o399001.ingest.sentry.io/5953495
    EXTERNAL_NODES:
      isEnabled: true
      stage: SECONDARY
    HIDDEN_NAMESPACES:
      isEnabled: true
      config:
        namespaces:
          - istio-system
          - kube-system
    GZIP:
      isEnabled: true
    EXTENSIBILITY:
      isEnabled: true
    EXTENSIBILITY_INJECTIONS:
      isEnabled: true
    EXTENSIBILITY_CUSTOM_COMPONENTS:
      isEnabled: false
    EXTENSIBILITY_WIZARD:
      isEnabled: false
    KYMA_COMPANION:
      isEnabled: true
      config:
        feedbackLink: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        documentationLink: https://help.sap.com/docs/btp/sap-business-technology-platform-internal/kyma-companion?locale=en-US&version=Internal&state=DRAFT
        model: 'gpt-4.1'
        queryMaxTokens: 8000
    GARDENER_LOGIN:
      isEnabled: false
      kubeconfig: null
    RESOURCE_VALIDATION:
      isEnabled: true
      config:
        policies:
          - Default
    CLUSTER_VALIDATION:
      isEnabled: true
    FEEDBACK:
      isEnabled: true
      link: https://sapinsights.eu.qualtrics.com/jfe/form/SV_d3UPNymSgUHAb9Y?product=SAP%20BTP,%20Kyma%20Runtime&product_filter=Kyma
    SNOW:
      isEnabled: false
    COMMUNITY_MODULES:
      isEnabled: true
