kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: testresources.busola.example.com
spec:
  group: busola.example.com
  names:
    plural: testresources
    singular: testresource
    shortNames:
      - tr
    kind: TestResource
    listKind: TestResourceList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A custom test resource for testing
          type: object
          properties:
            spec:
              description: Information about the resource
              type: object
              properties:
                name:
                  description: Simple name
                  type: string
                advancedName:
                  description: Advanced name object
                  type: object
                  properties:
                    name:
                      type: string
                      description: Advanced name
                    type:
                      description: Advanced name type
                      type: string
  conversion:
    strategy: None
