apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: cloudflare-dns-provider
  namespace: default #this needs to be defaut
  # Uncomment when using on Gardener cluster
  annotations:
    dns.gardener.cloud/class: garden
spec:
  type: cloudflare-dns
  secretRef:
    name: cloudflare-credentials
  domains:
    include:
      - kyma.cloud
      - '*.kyma.cloud'
      - '*.apirules.kyma.cloud'
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: apirules-cloudflare-dnsentry
  namespace: default
  # Uncomment when using on Gardener cluster
  annotations:
    dns.gardener.cloud/class: garden
spec:
  dnsName: '*.apirules.kyma.cloud'
  ttl: 600
  targets:
    - 34.90.219.247 # edit this value 34.91.46.115
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging-cloudflare
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-mail@domain.com
    autoRegistration: true
    # Name of the Secret used to store the ACME account private key
    # If doesn't exist, a new one is created
    privateKeySecretRef:
      name: letsencrypt-staging-cloudflare-secret
      namespace: default
    domains:
      include:
        - kyma.cloud
        - '*.kyma.cloud'
        - '*.apirules.kyma.cloud'
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: apirules-cloudflare-api-tls
  namespace: istio-system
  # annotations:
  #   dns.gardener.cloud/class: garden
spec:
  secretName: apirules-cloudflare-api-tls-credentials
  commonName: '*.apirules.kyma.cloud'
  issuerRef:
    name: letsencrypt-staging-cloudflare
    namespace: default
  # dnsNames:
  # - "*.apirules.kyma.cloud"

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apirules-cloudflare-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 443
        name: https-apirules
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: apirules-cloudflare-api-tls-7f989
      hosts:
        - '*.apirules.kyma.cloud'
