config:
  features:
    GZIP:
      isEnabled: true
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.stage.kyma.cloud.sap'
        tokenUrl: 'https://kymacanary.accounts.ondemand.com/oauth2/token'
