config:
  features:
    ALLOW_PRIVATE_IPS:
      isEnabled: false
    GZIP:
      isEnabled: true
    JWT_CHECK_CONFIG:
      isEnabled: true
      config:
        issuer: https://apskyxzcl.accounts400.ondemand.com
        jwksUri: https://apskyxzcl.accounts400.ondemand.com/.well-known/jwks.json
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.stage.kyma.cloud.sap'
        tokenUrl: 'https://kymacanary.accounts.ondemand.com/oauth2/token'
