apiVersion: v1
data:
  config: |
    {

      "config": {
        "storage": "localStorage",
        "features": {
          "LEGAL_LINKS": {
            "config": {
              "legal-disclosure": {
                "default": "https://www.sap.com/corporate/en/legal/impressum.html",
                "de": "https://www.sap.com/corporate/de/legal/impressum.html"
              },
              "privacy": {
                "default":
                  "https://help.sap.com/viewer/82bdf2271c6041f79387c122147cf774/Cloud/en-US"
              },
              "copyright": {
                "default": "https://www.sap.com/corporate/en/legal/copyright.html",
                "de": "https://www.sap.com/corporate/de/legal/copyright.html"
              },
              "trademark": {
                "default": "https://www.sap.com/corporate/en/legal/trademark.html",
                "de": "https://www.sap.com/corporate/de/legal/trademark.html"
              }
            }
          },
          "GET_HELP_LINKS": {
            "config": {
              "kyma-project-io": {
                "default": "https://kyma-project.io"
              },
              "help-sap-com": {
                "default": "https://help.sap.com"
              }
            }
          },
          "SENTRY": {
            "isEnabled": true,
            "selectors": [],
            "config": {
              "dsn": ""
            }
          },
          "KUBECONFIG_ID": {
            "config": {
              "kubeconfigUrl": "/kubeconfig"
            }
          },
          "GZIP": {
            "isEnabled": true
          },
          "VISUAL_RESOURCES": {
            "isEnabled": true
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: busola-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
    - name: http
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: busola
  name: web
spec:
  ports:
    - name: http-web
      port: 8080
      targetPort: 8080
  selector:
    app: busola
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: ADDRESS
              value: 0.0.0.0
          image: europe-docker.pkg.dev/kyma-project/prod/busola-backend:v0.0.1
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 3001
              name: http-backend
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128M
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - configMap:
            items:
              - key: config
                path: config.yaml
            name: busola-config
          name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busola
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busola
  template:
    metadata:
      labels:
        app: busola
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: environment
          image: europe-docker.pkg.dev/kyma-project/prod/busola-web:v0.0.1
          imagePullPolicy: Always
          name: busola
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 21Mi
          volumeMounts:
            - mountPath: /app/core-ui/config
              name: config
      volumes:
        - configMap:
            items:
              - key: config
                path: config.yaml
            name: busola-config
          name: config
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: busola
  name: backend
spec:
  maxReplicas: 11
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 125
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 125
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: busola
  name: web
spec:
  maxReplicas: 11
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
