# ---- Base Alpine with Node ----
FROM --platform=$BUILDPLATFORM node:24.13-alpine3.23 AS builder
ARG default_tag
ARG tag

# Install global dependencies
RUN apk update && \
  apk upgrade && \
  apk add --no-cache make yq

WORKDIR /app

# Set env variables
ENV PRODUCTION=true
ENV CI=true

COPY . /app
# build arg `tag` is used because `default_tag` is used by image builder and it cannot be overwritten.
RUN export TAG=${tag:-$default_tag} &&  yq -i '.version = "'${TAG}'"' public/version.yaml && \
  make resolve validate

RUN npm run build:docker

# ---- Environments Configuration ----
FROM --platform=$BUILDPLATFORM node:24.13-alpine3.23 AS configuration
WORKDIR /kyma

RUN apk add make

#Copy /kyma configuration into container to /kyma
COPY /kyma /kyma

RUN npm ci
RUN make prepare-configuration

# ---- Serve ----
FROM nginxinc/nginx-unprivileged:1.29.3-alpine3.22
WORKDIR /app

# apps
COPY --from=builder /app/build /app/core-ui

# nginx
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/
COPY --from=builder /app/nginx/mime.types /etc/nginx/

#entrypoint
COPY --from=builder --chown=nginx /app/start_nginx.sh /app/start_nginx.sh

#environment configuration
COPY --from=configuration /kyma/build /app/core-ui/environments

USER root:root
RUN chown -R nginx:root /etc/nginx /app/core-ui
USER nginx:nginx

ENV ENVIRONMENT=""

EXPOSE 8080
ENTRYPOINT ["/app/start_nginx.sh"]
