apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kyma-modules-fast-channel:operator.kyma-project.io/ModuleTemplate:kcp-system/serverless-fast
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.kyma-project.io/v1beta2","kind":"ModuleTemplate","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kyma-modules-fast-channel:operator.kyma-project.io/ModuleTemplate:kcp-system/serverless-fast","operator.kyma-project.io/doc-url":"https://kyma-project.io/#/serverless-manager/user/README","operator.kyma-project.io/is-cluster-scoped":"false","operator.kyma-project.io/module-version":"1.6.5"},"labels":{"argocd.argoproj.io/instance":"kyma-modules-fast-channel","operator.kyma-project.io/module-name":"serverless"},"name":"serverless-fast","namespace":"kcp-system"},"spec":{"channel":"fast","data":{"apiVersion":"operator.kyma-project.io/v1alpha1","kind":"Serverless","metadata":{"name":"default","namespace":"kyma-system"},"spec":{"dockerRegistry":{"enableInternal":true}}},"descriptor":{"component":{"componentReferences":[],"labels":[{"name":"security.kyma-project.io/scan","value":"enabled","version":"v1"}],"name":"kyma-project.io/module/serverless","provider":"{\"name\":\"kyma-project.io\",\"labels\":[{\"name\":\"kyma-project.io/built-by\",\"value\":\"cli\",\"version\":\"v1\"}]}","repositoryContexts":[{"baseUrl":"europe-docker.pkg.dev/kyma-project/modules-internal","componentNameMapping":"urlPath","type":"OCIRegistry"}],"resources":[{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/serverless-operator:1.6.5","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"serverless-operator","relation":"external","type":"ociImage","version":"1.6.5"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/function-controller:1.6.5","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"function-controller","relation":"external","type":"ociImage","version":"1.6.5"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/function-build-init:1.6.5","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"function-build-init","relation":"external","type":"ociImage","version":"1.6.5"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"registry-init","relation":"external","type":"ociImage","version":"v20240506-57d31b1d"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:1.6.5","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"function-runtime-nodejs20","relation":"external","type":"ociImage","version":"1.6.5"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:1.6.5","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"function-runtime-nodejs22","relation":"external","type":"ociImage","version":"1.6.5"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:1.6.5","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"function-runtime-python312","relation":"external","type":"ociImage","version":"1.6.5"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/external/gcr.io/kaniko-project/executor:v1.23.2","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"executor","relation":"external","type":"ociImage","version":"v1.23.2"},{"access":{"imageReference":"europe-docker.pkg.dev/kyma-project/prod/external/library/registry:2.8.3-v1","type":"ociRegistry"},"labels":[{"name":"scan.security.kyma-project.io/type","value":"third-party-image","version":"v1"}],"name":"registry","relation":"external","type":"ociImage","version":"2.8.3-v1"},{"access":{"localReference":"sha256:924e3d6f101211ed33252a0b39b4dbab00225189fc5bb7fa10f67c1ed06dadb1","mediaType":"application/octet-stream","referenceName":"raw-manifest","type":"localBlob"},"digest":{"hashAlgorithm":"SHA-256","normalisationAlgorithm":"genericBlobDigest/v1","value":"924e3d6f101211ed33252a0b39b4dbab00225189fc5bb7fa10f67c1ed06dadb1"},"name":"raw-manifest","relation":"local","type":"yaml","version":"1.6.5"}],"sources":[{"access":{"commit":"4f9a30389606188505dbd46dd2acdecb70687b8d","repoUrl":"https://github.com/kyma-project/serverless-manager.git","type":"gitHub"},"labels":[{"name":"git.kyma-project.io/ref","value":"HEAD","version":"v1"},{"name":"scan.security.kyma-project.io/rc-tag","value":"1.5.0","version":"v1"},{"name":"scan.security.kyma-project.io/language","value":"golang-mod","version":"v1"},{"name":"scan.security.kyma-project.io/dev-branch","value":"","version":"v1"},{"name":"scan.security.kyma-project.io/subprojects","value":"false","version":"v1"},{"name":"scan.security.kyma-project.io/exclude","value":"**/test/**,**/*_test.go","version":"v1"}],"name":"module-sources","type":"Github","version":"1.6.5"}],"version":"1.6.5"},"meta":{"schemaVersion":"v2"}},"mandatory":false}}
    operator.kyma-project.io/doc-url: https://kyma-project.io/#/serverless-manager/user/README
    operator.kyma-project.io/is-cluster-scoped: 'false'
    operator.kyma-project.io/module-version: 1.6.5
  labels:
    argocd.argoproj.io/instance: kyma-modules-fast-channel
    operator.kyma-project.io/managed-by: kyma
    operator.kyma-project.io/module-name: serverless
  name: serverless-fast
  namespace: kyma-system
spec:
  associatedResources:
    - group: serverless.kyma-project.io
      kind: Function
      version: v1alpha2
  channel: fast
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Serverless
    metadata:
      name: default
      namespace: kyma-system
    spec:
      dockerRegistry:
        enableInternal: true
  descriptor:
    component:
      componentReferences: []
      labels:
        - name: security.kyma-project.io/scan
          value: enabled
          version: v1
      name: kyma-project.io/module/serverless
      provider: '{"name":"kyma-project.io","labels":[{"name":"kyma-project.io/built-by","value":"cli","version":"v1"}]}'
      repositoryContexts:
        - baseUrl: europe-docker.pkg.dev/kyma-project/modules-internal
          componentNameMapping: urlPath
          type: OCIRegistry
      resources:
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:1.6.5
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: serverless-operator
          relation: external
          type: ociImage
          version: 1.6.5
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/function-controller:1.6.5
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: function-controller
          relation: external
          type: ociImage
          version: 1.6.5
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/function-build-init:1.6.5
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: function-build-init
          relation: external
          type: ociImage
          version: 1.6.5
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: registry-init
          relation: external
          type: ociImage
          version: v20240506-57d31b1d
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:1.6.5
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: function-runtime-nodejs20
          relation: external
          type: ociImage
          version: 1.6.5
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:1.6.5
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: function-runtime-nodejs22
          relation: external
          type: ociImage
          version: 1.6.5
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:1.6.5
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: function-runtime-python312
          relation: external
          type: ociImage
          version: 1.6.5
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/external/gcr.io/kaniko-project/executor:v1.23.2
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: executor
          relation: external
          type: ociImage
          version: v1.23.2
        - access:
            imageReference: europe-docker.pkg.dev/kyma-project/prod/external/library/registry:2.8.3-v1
            type: ociRegistry
          labels:
            - name: scan.security.kyma-project.io/type
              value: third-party-image
              version: v1
          name: registry
          relation: external
          type: ociImage
          version: 2.8.3-v1
        - access:
            localReference: sha256:924e3d6f101211ed33252a0b39b4dbab00225189fc5bb7fa10f67c1ed06dadb1
            mediaType: application/octet-stream
            referenceName: raw-manifest
            type: localBlob
          digest:
            hashAlgorithm: SHA-256
            normalisationAlgorithm: genericBlobDigest/v1
            value: 924e3d6f101211ed33252a0b39b4dbab00225189fc5bb7fa10f67c1ed06dadb1
          name: raw-manifest
          relation: local
          type: yaml
          version: 1.6.5
      sources:
        - access:
            commit: 4f9a30389606188505dbd46dd2acdecb70687b8d
            repoUrl: https://github.com/kyma-project/serverless-manager.git
            type: gitHub
          labels:
            - name: git.kyma-project.io/ref
              value: HEAD
              version: v1
            - name: scan.security.kyma-project.io/rc-tag
              value: 1.5.0
              version: v1
            - name: scan.security.kyma-project.io/language
              value: golang-mod
              version: v1
            - name: scan.security.kyma-project.io/dev-branch
              value: ''
              version: v1
            - name: scan.security.kyma-project.io/subprojects
              value: 'false'
              version: v1
            - name: scan.security.kyma-project.io/exclude
              value: '**/test/**,**/*_test.go'
              version: v1
          name: module-sources
          type: Github
          version: 1.6.5
      version: 1.6.5
    meta:
      schemaVersion: v2
  mandatory: false
  moduleName: ''
  version: ''
