apiVersion: batch/v1
kind: CronJob
metadata:
  name: hundred-fibonaccis
  namespace: default
  labels:
    app.kubernetes.io/name: hello
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - name: hundred-fibonaccis
              image: truek8s/hundred-fibonaccis:1.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
