apiVersion: batch/v1
kind: Job
metadata:
  name: memory-hog
  namespace: default
  labels:
    app.kubernetes.io/name: memory-hog
    istio-injection: disabled
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - name: memory-hog
          image: truek8s/memory-hog:1.0
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
