config:
  features:
    GZIP:
      isEnabled: true
    TRACKING:
      isEnabled: false
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.dev.kyma.cloud.sap'
        tokenUrl: 'https://kymatest.accounts400.ondemand.com/oauth2/token'
        skipAuth: false
