config:
  features:
    GZIP:
      isEnabled: true
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.dev.kyma.cloud.sap'
        tokenUrl: 'https://kymatest.accounts400.ondemand.com/oauth2/token'
        skipAuth: false
    ALLOW_PRIVATE_IPS:
      isEnabled: false
    KUBERNETES_PROXY:
      config:
        allowedPorts: [443, 6443, 8443]
    COMMUNITY_MODULES:
      config:
        allowedDomains:
          - githubusercontent.com
          - github.com
          - github.io
