config:
  features:
    GZIP:
      isEnabled: true
    JWT_CHECK_CONFIG:
      isEnabled: false
      config:
        issuer: https://apskyxzcl.accounts400.ondemand.com
        jwksUri: https://apskyxzcl.accounts400.ondemand.com/.well-known/jwks.json
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.dev.kyma.cloud.sap'
        tokenUrl: 'https://kymatest.accounts400.ondemand.com/oauth2/token'
        skipAuth: false
    ALLOW_PRIVATE_IPS:
      isEnabled: false
