apiVersion: v1
kind: Config
current-context: shoot--hasselhoff--kmain
contexts:
  - name: shoot--hasselhoff--kmain
    context:
      cluster: shoot--hasselhoff--kmain
      user: shoot--hasselhoff--kmain-token
  - name: shoot--kyma-prow--nkyma
    context:
      cluster: shoot--kyma-prow--nkyma
      user: shoot--kyma-prow--nkyma-token
clusters:
  - name: shoot--hasselhoff--kmain
    cluster:
      server: 'https://api.kmain.hasselhoff.shoot.canary.k8s-hana.ondemand.com'
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQUtHUWEvc3RxTHVhc1F4c0p5U01Wb1l3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpJd05qSXpNVEl3TkRRMldoY05Nekl3TmpJek1USXdORFEyV2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2dQCnlET1JlUmx4Nkdqb3ZXUlVTdSsyMjN5QnNFc0c2YXFNejdNWEhPZ2sxQWhiVURKSnhMWVBiWVJXR3gvMjlpaFYKdkJLeVNJOFc4a2xSY0VObWppN3BOTkxrNFBzMENLdEszOHJudlkrOFFZQi9FWHptWGdadkExYkduS2ozVXZaVwo1NVJqekV1UTB5S2U4VHlCYUpidFhGekV5S2luYVRqSWxZUkcwMmtrVHdtelJLSTltY3VXVFZjWnh1Sm5sVUJ2ClB4MHlXNUR2ZnhXVVl5OUhBZ0FJbGZPWEhEaWZWaHA2c0tQWHZ3VTFjRFg3WE1jMVp5MHBYelp2ZmNkRkNNQlQKcjU0aDFVR0tNNEcwc0VpUHJ4VFl2L0JxVGFHNUgxNlc5V0JjTGJrbXJkdklFdDRickZSVzdjd3BlN2ExTHIyZQpISG51RHpiTEs4Sy9mMGhWUHU4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPaHhySS9DdWVtV2kxV1ZvVWlNOFFpQW5icnJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCQUhSOEVtYVRyZEs3VTFVU3lKVFhpZlVkbDBpTXV5alRSazRJTWhmSEk1SENJM1dMZgpxRDJNbnhOR0Nxb0pIY0RRb0NoLys4cm5rUzJEclJkbzdiQm1VcU15eUNYcEFRZFcvSGFkdG5KRWhPbHRkY3RSCmhYa3oydHcwSm9IQ3RQL0t4T2x0anVPSHd4eUIzb01XUlFiVW93Zi9xaG03dERoR1dmTjF5U3YxWEZDV3NLZ2UKckczdThrSFJaT043S3BzaGhwRTZNdVQvbytFcUZNMTVWUlA0SjluVkFsQ2dkeU4rdURoeDI4Ni85WWRxMkhrYwpzUDBSdlhkTVB1c2dBL3BsUTRQeDVYdi9sdzdTUXhQWFdGQzU1U1JzOGVCU3JaOWd1dTVXRGVhQ2RiNmJZb3hkClZyRFlxdkpvN3U3dEN4UVZYMC9lK1NiOVNtWW05Zm5nQWtXZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  - name: shoot--kyma-prow--nkyma
    cluster:
      server: 'https://api.nkyma.kyma-prow.shoot.live.k8s-hana.ondemand.com'
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQUxCKzRZaHc1WisyMjZwL3dGNVF2eEl3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpJd056QTBNRE14TmpRNFdoY05Nekl3TnpBME1ETXhOalE0V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDhOClc4TW9kVy9jVHRxcFZGaDlIWVZEQzRrN0FOcW5WaUlkdDRvT3NrQ2xwK0U5cUE2OGJTSjFYUFVjRzJXNE5KMU4KbDZBeHFLQ2xseGFaVGN4WGR5Y05RWDFkL1ZJT3FhSlI3a1psc1lYTE1GdjdFVWkyNnRTQ005T29YK2RaUlM3UwppZCttQkFzR21YckhQR3Z4SmNuS1pPVDVEL2hlN2NvWFdTZlpZYnJEbm1HbFlQQkg5VFVCaURqcVF1KzZKQ25VCnBwQ3NDRnNiTHFxSDYwNDdZRllaTkZsZlcxSG9UTHE4NHZyaEJTYmdUVkI1K21ZY01LWG9mOTlvL2lYVVN0cVcKSlh5SmNnR3NOV1pBUlBPdVJjMkJwd0xzN0hRWUpnbnlPenF3amdmQmVpK2xZTnJoOS9rd0xPZmExNVlGMU9kZwpQVWNSZERtYnJmWXZWa3I1MkNVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMNTJYQzlvTGJ2dy9VWjRUTFhjNWNIb0pyN0lNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBZTh5TFRKalltMW1JcmZJQ3B1eWNJd1VOc1VnM20yaXU4aEZ0VS9TU1JRcmRRRFo4YgplZ2FHc0htOUFJS0NGSUJJM3BYYzlTZGJZdTRWcEkwSkVjbHdyMDVibnEzcFIycnhuaUZWL29iaWF6MklGRlpTCll0clZWbFhEYmJPMVNwYTI2czU2SEtNRFJvK1RHT0d3QTRWRkVFcTArOFVTenBXb2l6bjF2SjhqUTRGMUZFK0cKRGhEOVU1Qkl3MXN5UVgweXlSbVhyY2xFYk55SXBaVStxejBQNmFjYy9mc2g4Z0ZCQmVjdXpzdWdlK2UzZGtHego2VUdscWI2cjlPMDBGWmxsNGlZb1RQa3NyanhRYU9XOE1BNGJ0N24zbUpta3VGU2Q3NVRVckVHa05PbzFxWlRrCkdYZWs4aFdGN0NwWVovL05PMy9wclltNTdISmlLTjVUM3RuUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
users:
  - name: shoot--hasselhoff--kmain-token
    user:
      token: >-
        TLpPxNV1ctu3eh2AEWhcOChEzJTAVWgBbs2yPvNKMBWVVeaKDTBrE8hjOknmu3LmwStt7ohQMX1xj9LmSpvNgjdAJ5PmlRyy8tLMsOmA6f1x6VRwDPGdaMbNJP9FPFtl
  - name: shoot--kyma-prow--nkyma-token
    user:
      token: >-
        TXpnZU0uP282A3n0Y6MOfkosyua6hmIKVj04Ytik0wxS9zsF5gXrTrjUw4LOeut3fY7ScpKuNTVUB4S27aRZnj9pIRoxcB4z3FjP3almUN8MrKHm8BxBe5JxuQY9U8bh
