apiVersion: v1
kind: ConfigMap
metadata:
  name: kymas.operator.kyma-project.io
  namespace: kube-public
  labels:
    app.kubernetes.io/name: kymas.operator.kyma-project.io
    busola.io/extension: statics
    busola.io/extension-version: '0.5'
data:
  dataSources: |
    moduleTemplates:
      resource:
        kind: ModuleTemplate
        namespace: null
        group: operator.kyma-project.io
        version: v1beta2
  injections: |-
    - title: Introducing Modules
      name: Modules
      description: Modules add functionalities to your cluster. Consume SAP BTP services, monitor your cluster, build serverless applications and more.
      widget: FeaturedCard
      source: $
      id: ModulesBanner
      order: 0
      illustration: Modules
      design: information-1
      visiblity: false
      children:
        - widget: ResourceButton
          source: "'Add Modules'"
          visiblity: 'false'
          resource: 
            customUrl: kymamodules
        - widget: ExternalLinkButton
          link: https://help.sap.com/docs/btp/sap-business-technology-platform/kyma-s-modular-approach
      targets:
        - slot: banner
          location: ClusterOverview