apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend
  - web
images:
  - name: busola-web
    newName: europe-docker.pkg.dev/kyma-project/prod/busola-web
    newTag: latest
  - name: busola-backend
    newName: europe-docker.pkg.dev/kyma-project/prod/busola-backend
    newTag: latest
