apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - builtin-resource-extensions.configmap.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: web
    path: web-deployment.patch.yaml

bases:
  - ../web
