name: 'Merge'
description: 'Action for merging PR with the latest main branch'

runs:
  using: 'composite'
  steps:
    # Setup identity to avoid errors when git is trying to rebase without identity set
    - name: Setup git identity
      run: |
        git config --global user.email "merge@action.com"
        git config --global user.name "Merge Action"
      shell: bash

    # Update origin/main branch locally to cover case when repo is not fully cloned
    # for example when using `actions/checkout@v4` action with default `fetch-depth` value (1)
    # read more: https://github.com/actions/checkout?tab=readme-ov-file#usage
    - name: Update origin/main
      run: |
        git fetch origin main
        git checkout origin/main
        git checkout -B main
        git pull origin main

        # go back to the HEAD commit
        git switch --detach ${{ github.sha }}
      shell: bash

    - name: Merge with latest main
      run: |
        git merge main
      shell: bash

    - name: Print branch log
      run: |
        git log origin/main~1..
      shell: bash
