kind: ConfigMap
apiVersion: v1
metadata:
  name: dnsentries
  namespace: kube-public
  labels:
    app.kubernetes.io/name: dnsentries
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |-
    header: 
      - source: 'status.state ? status.state : "UNKNOWN"'
        highlights:
          informative:
            - UNKNOWN
        type: string
        name: status
        widget: Badge
        description: status.message
    body: 
      - name: Provider
        widget: Panel
        children:
          - name: Provider
            source: status.provider
      - name: Specification
        widget: Panel
        children:
          - name: spec.dnsName
            source: spec.dnsName 
          - name: TTL
            source: spec.ttl
          - name: spec.targets
            widget: JoinedArray
            source: spec.targets
  form: |-
    - simple: true
      path: spec.dnsName
      placeholder: dnsName.placeholder
      required: true
    - simple: true
      name: TTL
      placeholder: ttl.placeholder
      path: spec.ttl
      required: true
    - path: spec.targets
      widget: SimpleList
      simple: true
      defaultExpanded: true
      required: true    
      name: spec.targets
      children:
        - widget: Text
          simple: true
          placeholder: target.placeholder 
    - path: spec.text
      name: spec.text
      widget: SimpleList
      children:
        - path: '[]'
          simple: true  
      placeholder: text.placeholder
      defaultExpanded: true
  general: |
    resource:
      kind: DNSEntry
      group: dns.gardener.cloud
      version: v1alpha1
    name: DNS Entries
    category: Configuration
    urlPath: dnsentries
    scope: namespace
    description: >-
      {{[DNSEntry](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload/)}}
      is an object that represents the request to create an external DNS record.
  list: |-
    - source: 'status.state ? status.state : "UNKNOWN"'
      highlights:
        informative:
          - UNKNOWN
      type: string
      name: status
      widget: Badge
      description: status.message
  presets: |-
    - name: template
      default: true
      value:
        metadata:
          annotations: 
            dns.gardener.cloud/class: garden 
        spec:
          ttl: 600
          dnsName: ''
          targets: []
          text: []
          items: []
          name: ''
          bool: false
  translations: |-
    en: 
      metadata.annotations: Annotations
      metadata.labels: Labels
      metadata.creationTimestamp: Created at
      target.placeholder: Enter the A record target or CNAME record
      spec.targets: Targets
      spec.dnsName: DNSName
      ttl.placeholder: Enter the time to live
      spec.text: Text
      dnsName.placeholder: Select the DNSName
      text.placeholder: Text record must be a string. Provide either target or text. 
      status: Status
