kind: ConfigMap
apiVersion: v1
metadata:
  name: dnsproviders
  namespace: kube-public
  labels:
    app.kubernetes.io/name: dnsproviders
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |-
    header:
      - source: spec.type
        name: spec.type
      - source: 'status.state ? status.state : "UNKNOWN"'
        highlights:
          informative:
          - UNKNOWN
        type: string
        name: status
        widget: Badge
        description: status.message
    body:
      - widget: Columns
        children:
        - name: included.domains 
          widget: Table
          showHeader: false
          source: spec.domains.include
          children:
            - source: $item
              search: true
        - name: excluded.domains
          widget: Table
          showHeader: false
          source: spec.domains.exclude
          children:
            - source: $item
              search: true
  form: |-
    - simple: true
      path: spec.type
      widget: Text
      placeholder: provider.choose
      enum:
        - alicloud-dns
        - aws-route53
        - azure-dns
        - google-clouddns
        - openstack-designate
        - cloudflare-dns
        - infoblox-dns
        - netlify-dns
      required: true
    - name: spec.secretRef
      simple: true
      path: spec.secretRef
      widget: ResourceRef      
      provideVar: secret
      resource:
        kind: Secret
        version: v1
      defaultExpanded: true
      required: true 
    - path: spec.domains.include
      simple: true
      widget: SimpleList
      children:
        - path: '[]'
          simple: true
      placeholder: domain.allowed
      defaultExpanded: true
      required: true
    - path: spec.domains.exclude
      widget: SimpleList
      children:
        - path: '[]'
      placeholder: domain.forbidden
  general: |-
    resource:
      kind: DNSProvider
      group: dns.gardener.cloud
      version: v1alpha1
    name: DNS Providers
    category: Configuration
    urlPath: dnsproviders
    scope: namespace
    description: >-
      {{[DNSProvider](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain)}}
      is used to specify and manage the configuration for the external DNS services.
  list: |-
    - name: spec.type
      source: spec.type
    - source: 'status.state ? status.state : "UNKNOWN"'
      highlights:
        informative:
        - UNKNOWN
      name: status
      widget: Badge
      description: status.message
  presets: |-
    - name: template
      default: true
      value: 
        metadata:
          annotations: 
            dns.gardener.cloud/class: garden
        spec:
          domains:
            include: []
            exclude: []
          secretRef:
            name: ''
            namespace: ''
          type: ''
  translations: |-
    en:
      metadata.annotations: Annotations
      metadata.labels: Labels
      metadata.creationTimestamp: Created at
      provider.choose: Choose Provider type
      spec.type: Type
      spec.type.alicloud-dns: Alicloud DNS provider
      spec.type.aws-route53: AWS Route 53 provider
      spec.type.azure-dns: Azure DNS provider
      spec.type.google-clouddns: Google CloudDNS provider
      spec.type.openstack-designate: Openstack Designate provider
      spec.type.cloudflare-dns: Cloudflare DNS provider
      spec.type.infoblox-dns: Infoblox DNS provider
      spec.type.netlify-dns: Netlify DNS provider
      spec.domains.include: Include Domains
      spec.domains.exclude: Exclude Domains
      included.domains: Included Domains
      excluded.domains: Excluded Domains
      domain.allowed: Domain that is allowed
      domain.forbidden: Domain that is forbidden
      spec.secretRef: Secret Reference
      status: Status
