kind: ConfigMap
apiVersion: v1
metadata:
  name: gateways
  namespace: kube-public
  labels:
    app.kubernetes.io/name: gateways
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: |-
    { 
      "gateways":{
        "resource": {
          "kind": "Gateway",
          "group": "networking.istio.io",
          "version": "v1beta1"
        }
      }
    }
  details: |
    {
      "header": [
        {
          "path": "spec.selector",
          "source": "spec.selector",
          "widget": "Labels"
        }
      ],
      "body":[     
        {
          "widget": "Table",
          "path": "spec.servers",
          "children": [
            { "path": "port.name" },
            { "path": "hosts" },
            { "path": "port.number" },
            { "path": "tls.mode" },
            { "path": "tls.credentialName" }
          ]
        },
      ]
    }
  form: |-
    [
      {
        "path": "spec.selector", "widget": "KeyValuePair", "simple": true
      }
    ]
  general: |-
    {
      "resource": {
        "kind": "Gateway",
        "group": "networking.istio.io",
        "version": "v1beta1"
      },
      "urlPath": "cherry-gateways",
      "category": "Cherry",
      "scope": "namespace",
      "description": "{{[Gateways](https://istio.io/latest/docs/reference/config/networking/gateway/)}} describes a load balancer that operates at the edge of the mesh and receives incoming or outgoing HTTP/TCP connections. ."
    }
  list: |-
    [
      { 
        "path": "spec.selector",
        "widget": "Labels"
      },
    ]
  translations: |
    en:
      spec.selector: Selector
      spec.gateways: Gateways
      spec.servers: Servers
      spec.servers.port.name: Name
      spec.servers.hosts: Hosts
      spec.servers.port.number: Port
      spec.servers.tls.mode: TLS Mode
      spec.servers.tls.credentialName: TLS Secret
