kind: ConfigMap
apiVersion: v1
metadata:
  name: gateways
  namespace: kube-public
  labels:
    app.kubernetes.io/name: gateways
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: |-
    {
      "podSelector": {
        "resource": {
          "kind": "Pod",
          "version": "v1",
        },
        "filter": "$filter(data, function($item) { $selectorMatchByLabels($item, resource.spec.selector) })"
      }
    }
  details: |
    {
      "header": [
        {
          "path": "spec.selector",
          "source": "spec.selector",
          "widget": "Labels"
        }
      ],
      "body": [     
        {
          "widget": "Table",
          "path": "spec.servers",
          "children": [
            { "path": "port.name" },
            { "path": "hosts" },
            { "path": "port.number" },
            { "path": "tls.mode" },
            { "path": "tls.credentialName" }
          ]
        },
        {
          "widget": "Panel",
          "name": "Selector",
          "children": [
            { 
              "path": "$podSelector",
              "widget": "ResourceList",
              "disableCreate": true,
              "isCompact": true
            }
          ]
        }
      ]
    }
  form: |-
    [
      {
        "path": "spec.selector", "widget": "KeyValuePair", "simple": true
      },
      {
        "widget": "FormGroup",
        "simple": true,
        "path": "spec.servers[].port",
        "children": [
          { "path": "number", "simple": true },
          { "path": "name", "widget": "Name", "showHelp": false, "simple": true },
          {
            "path": "protocol", 
            "simple": true,
            "enum": [
              "HTTP",
              "HTTPS",
              "HTTP2",
              "GRPC",
              "GRPC-WEB",
              "MONGO",
              "REDIS",
              "MYSQL",
              "TCP"
            ],
          },
          { "path": "targetPort", "simple": true },
        ]
      },
      {
        "widget": "FormGroup",
        "simple": true,
        "path": "spec.servers[].tls",
        "visibility": "$item.port.protocol = 'HTTP' or $item.port.protocol = 'HTTPS'",
        "children": [
          { "path": "httpsRedirect", "simple": true, "visibility": "$item.port.protocol = 'HTTP'" },
          { 
            "path": "mode", 
            "simple": true, 
            "visibility": "$item.port.protocol = 'HTTPS'",
            "enum": [ ],
          },
          { "path": "credentialName", "simple": true, "visibility": "$item.port.protocol = 'HTTPS'" },
          { "path": "serverCertificate", "simple": true, "visibility": "$item.port.protocol = 'HTTPS'" },
          { "path": "privateKey", "simple": true, "visibility": "$item.port.protocol = 'HTTPS'" },
          { "path": "caCertificates", "simple": true, "visibility": "$item.port.protocol = 'HTTPS'" },
        ]
      },
      {
        "widget": "SimpleList",
        "path": "spec.servers[].hosts", "simple": true
      }
    ]
  general: |-
    {
      "resource": {
        "kind": "Gateway",
        "group": "networking.istio.io",
        "version": "v1beta1"
      },
      "urlPath": "cherry-gateways",
      "category": "Istio",
      "scope": "namespace",
      "description": "{{[Gateways](https://istio.io/latest/docs/reference/config/networking/gateway/)}} describes a load balancer that operates at the edge of the mesh and receives incoming or outgoing HTTP/TCP connections. ."
    }
  list: |-
    [
      { 
        "path": "spec.selector",
        "widget": "Labels"
      },
    ]
  translations: |
    en:
      spec.selector: Selector
      spec.gateways: Gateways
      spec.servers: Servers
      spec.servers.port: Port
      spec.servers.port.name: Name
      spec.servers.port.protocol: Protocol
      spec.servers.port.targetPort: Target Port
      spec.servers.port.number: Port Number
      spec.servers.tls: TLS
      spec.servers.tls.mode: TLS Mode
      spec.servers.tls.httpsRedirect: HTTP Redirect
      spec.servers.tls.credentialName: Credential Name
      spec.servers.tls.serverCertificate: Server Certificate
      spec.servers.tls.privateKey: Private Key
      spec.servers.tls.caCertificates: CA Certificate
      spec.servers.hosts: Hosts
