kind: ConfigMap
apiVersion: v1
metadata:
  name: servicebindings.services.cloud.sap.com
  namespace: kube-public
  labels:
    app.kubernetes.io/name: servicebindings.services.cloud.sap.com
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |-
    header:
      - name: Controlled By
        source: spec.controlledBy
      - name: Status
        source: status.conditions[0].reason
        widget: Badge
    body:
      - name: Binding Data
        widget: Panel
        children:
          - name: Service Instance Name
            source: spec.serviceInstanceName
          - name: Secret
            source: spec.secretName
          - name: External Name
            source: spec.externalName
          - name: Binding ID
            source: spec.bindingID
          - name: Instance ID
            source: spec.instanceID
      - name: Parameters
        source: spec.parameters
        widget: CodeViewer
        language: 'javascript'
      - name: Parameters from Secrets
        source: spec.parametersFrom
        widget: CodeViewer
        language: 'javascript'
  form: |-
    - simple: true
      path: spec.serviceInstanceName
      required: true
      placeholder: Start typing to select Service Binding from the list
      enum: 
        []
    - name: External Name
      path: spec.externalName
      placeholder: Defaults to the Service Binding name if empty
    - name: Secret
      path: spec.secretName
    - name: Parameters
      path: spec.parameters
      defaultExpanded: false
      widget: KeyValuePair

    - name: Parameters from Secrets
      path: spec.parametersFrom
      widget: KeyValuePair
      placeholder: Choose Secret
      keyEnum:
        - dreary-bed
        - serverless-registry-config-default
      value:
        type: object
        valueEnum:
          - blub
          - blob
  general: |-
    resource:
      kind: ServiceBinding
      group: services.cloud.sap.com
      version: v1
    name: Service Bindings
    category: Custom Resources
    urlPath: servicebindings-test
    scope: namespace
    description: >-
      {{[BTP Service Binding](https://github.com/SAP/sap-btp-service-operator#step-2-create-a-service-binding)}}
      provides access details for an existing service instance.
  list: |-
    - name: Controlled By
      source: spec.controlledBy
    - name: Service Instance Name
      source: spec.serviceInstanceName
    - name: External Name
      source: spec.externalName
    - name: Status
      widget: Badge
      description: status.message
      source: status.conditions[1].reason
  presets: |-
    - name: template
      default: true
      value: 
        spec:
          serviceInstanceName: ''
          externalName: ''
          secretName: ''
          parameters: {}
          parametersFrom: []
  translations: |-
    en:
      metadata.annotations: Annotations
      metadata.labels: Labels
      metadata.creationTimestamp: Created at
