kind: ConfigMap
apiVersion: v1
metadata:
  name: busola-config
data:
  config: >
    {
      "config": {
        "storage": "localStorage",
        "features": {
          "LEGAL_LINKS": {
            "config": {
              "legal-disclosure": {
                "default": "https://www.sap.com/corporate/en/legal/impressum.html",
                "de": "https://www.sap.com/corporate/de/legal/impressum.html"
              },
              "privacy": {
                "default":
                  "https://help.sap.com/viewer/82bdf2271c6041f79387c122147cf774/Cloud/en-US"
              },
              "copyright": {
                "default": "https://www.sap.com/corporate/en/legal/copyright.html",
                "de": "https://www.sap.com/corporate/de/legal/copyright.html"
              },
              "trademark": {
                "default": "https://www.sap.com/corporate/en/legal/trademark.html",
                "de": "https://www.sap.com/corporate/de/legal/trademark.html"
              }
            }
          },
          "GET_HELP_LINKS": {
            "config": {
              "kyma-project-io": {
                "default": "https://kyma-project.io"
              },
              "help-sap-com": {
                "default": "https://help.sap.com"
              }
            }
          },
          "SENTRY": {
            "isEnabled": true,
            "selectors": [],
            "config": {
              "dsn": ""
            }
          },
          "KUBECONFIG_ID": {
            "config": {
              "kubeconfigUrl": "/kubeconfig"
            }
          },
          "GZIP": {
            "isEnabled": true
          },
          "VISUAL_RESOURCES": {
            "isEnabled": true
          }
        }
      }
    }
