apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: busola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busola
  template:
    metadata:
      labels:
        app: busola
    spec:
      containers:
        - name: busola
          image: busola-web
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  optional: true
                  key: ENVIRONMENT
                  name: environment
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  optional: true
                  key: BACKEND_URL
                  name: busola-config
          resources:
            requests:
              cpu: 100m
              memory: 21Mi
          ports:
            - containerPort: 8080
