apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecars.networking.istio.io
  namespace: ak
  labels:
    app.kubernetes.io/name: sidecars.networking.istio.io
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: |-
    {
      "podSelector": {
        "resource": {
          "kind": "Pod",
          "version": "v1",
        },
        "filter": "$matchByLabelSelector($item, $root.spec.workloadSelector.labels)"
      }
    }
  details: |-
    {
      "header": [{ 
        "name": "spec.outboundTrafficPolicy.mode",
        "source": "spec.outboundTrafficPolicy.mode"
        }],
      "body": [
        {
          "widget": "Table",
          "source": "spec.egress",
          "name": "Egress",
          "visibility": "$exists(*)",
          "children": [
            {
              "source": "$item.port", 
              "name": "item.port", 
              "widget": "Panel", 
              "visibility": "$exists(*)",
              "children": [
                { "source": "$item.number", "name": "item.port.number" },
                { "source": "$item.protocol", "name": "item.port.protocol" },
                { "source": "$item.name", "name": "item.port.name" },
                { "source": "$item.targetPoint", "name": "item.port.targetPoint" },
              ] 
            },
            { "source": "$item.bind", "name": "item.bind" },
            { "source": "$item.captureMode", "name": "item.captureMode" },
            { "source": "$item.hosts", "name": "item.hosts", "widget": "Labels"}
          ]
        },
        {
          "widget": "Table",
          "source": "spec.ingress",
          "name": "Ingress",
          "visibility": "$exists(*)",
          "children": [
            {
              "source": "$item.port", 
              "name": "item.port", 
              "widget": "Panel", 
              "visibility": "$exists(*)",
              "children": [
                { "source": "$item.number", "name": "item.port.number" },
                { "source": "$item.protocol", "name": "item.port.protocol" },
                { "source": "$item.name", "name": "item.port.name" },
                { "source": "$item.targetPoint", "name": "item.port.targetPoint" },
              ] 
            },
            { "source": "$item.bind", "name": "item.bind" },
            { "source": "$item.captureMode", "name": "item.captureMode" },
            { "source": "$item.defaultEndpoint", "name": "item.defaultEndpoint", "widget": "Labels"}
          ]
        },
        {
          "widget": "Panel",
          "name": "spec.workloadSelector",
          "disablePadding": true,
          "children": [
            { 
              "source": "$podSelector()",
              "widget": "ResourceList",
              "disableCreate": true,
              "isCompact": true,
              "visibility": "$boolean($root.spec.workloadSelector.labels)"
            },
            {
              "source": "spec.workloadSelector.labels",
              "widget": "Panel",
              "name": "selector.matchesAllPods",
              "visibility": "$not($exists(*)) or $not($boolean(*))"
            }
          ],
          "header": [
            {
              "source": "spec.workloadSelector.labels",
              "widget": "Labels",
              "name": "spec.workloadSelector.labels",
              "visibility": "$boolean(*)"
            }
          ],
        }
      ]
    }
  form: |-
    [
      {
        "path": "spec.workloadSelector.labels", 
        "widget": "KeyValuePair"      },
      {
        "widget": "FormGroup",
        "path": "spec.ingress[].port",
        "required": true,
        "children": [
          { 
            "path": "number", 
            "simple": true,
            "required": true
          },
          { 
            "path": "name", 
            "widget": "Name", 
            "showHelp": false, 
            "simple": true ,
            "required": true
          },
          {
            "path": "protocol", 
            "simple": true,
            "enum": [
              "HTTP",
              "HTTPS",
              "HTTP2",
              "GRPC",
              "MONGO",
              "TCP",
              "TLS"
            ],
            "required": true,
            "placeholder": "placeholders.dropdown",
          },
          { "path": "targetPort", "simple": true },
        ]
      },
      {
        "widget": "FormGroup",
        "path": "spec.ingress[].bind"
      },
      {
        "widget": "FormGroup",
        "path": "spec.ingress[].captureMode",
        "enum": [
          "DEFAULT",
          "IPTABLES",
          "NONE"
        ],
        "placeholder": "placeholders.dropdown",
      },
      {
        "widget": "FormGroup",
        "path": "spec.ingress[].defaultEndpoint",
        "required": true,
      },
      {
        "widget": "FormGroup",
        "path": "spec.egress[].port",
        "children": [
          { 
            "path": "number", 
            "simple": true,
            "required": true
          },
          { 
            "path": "name", 
            "widget": "Name", 
            "showHelp": false, 
            "simple": true ,
            "required": true
          },
          {
            "path": "protocol", 
            "simple": true,
            "enum": [
              "HTTP",
              "HTTPS",
              "HTTP2",
              "GRPC",
              "MONGO",
              "TCP",
              "TLS"
            ],
            "required": true,
            "placeholder": "placeholders.dropdown",
          },
          { "path": "targetPort", "simple": true },
        ]
      },
      {
        "widget": "FormGroup",
        "path": "spec.egress[].bind"
      },
      {
        "widget": "FormGroup",
        "path": "spec.egress[].captureMode",
        "enum": [
          "DEFAULT",
          "IPTABLES",
          "NONE"
        ],
        "placeholder": "placeholders.dropdown",
      },
      {
        "widget": "SimpleList",
        "path": "spec.egress[].hosts", 
        "required": true,
        "placeholder": "placeholders.hosts"
      },
      {
        "widget": "FormGroup",
        "path": "spec.outboundTrafficPolicy",
        "children": [{
          "path": "mode", 
          "name": "spec.outboundTrafficPolicy.mode",
          "enum": [
            "REGISTRY_ONLY",
            "ALLOW_ANY"
          ],
          "placeholder": "placeholders.dropdown",
        }]
      }
    ]
  general: |-
    {
      "resource": {
        "kind": "Sidecar",
        "group": "networking.istio.io",
        "version": "v1alpha3"
      },
      "urlPath": "ext-sidecars",
      "category": "Istio",
      "name": "Ext Sidecars",
      "scope": "namespace",
      "description": "{{[Sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/)}} manages the incoming and outgoing communication in a workload it is attached to."

    }
  list: |-
    [
      { "source": "spec.outboundTrafficPolicy.mode","name": "spec.outboundTrafficPolicy.mode"},
      { "source": "spec.workloadSelector.labels", "name": "spec.workloadSelector.labels", "widget": "Labels"}
    ]
  translations: |-
    {
      "en": {
        "metadata.annotations": "Annotations",
        "metadata.labels": "Labels",
        "spec.outboundTrafficPolicy": "Outbound Traffic Policy",
        "spec.outboundTrafficPolicy.mode": "Outbound Traffic Policy Mode",
        "spec.workloadSelector": "Workload Selector",
        "spec.workloadSelector.labels": "Workload Selector Labels",
        "item.bind": "Bind",
        "item.captureMode": "Capture Mode",
        "item.defaultEndpoint": "Default Endpoint",
        "item.hosts": "Hosts",
        "item.port": "Port",
        "item.port.number": "Port Number",
        "item.port.protocol": "Protocol",
        "item.port.name": "Port Name",
        "item.port.targetPoint": "Target Point",
        "placeholders.dropdown": "Type or choose an option",
        "selector.matchesAllPods": "Matches all Pods in the Namespace",
        "placeholders.hosts": "For example, *.api.mydomain.com"
      }
    }
