kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: serviceinstances.services.cloud.sap.com
spec:
  group: services.cloud.sap.com
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    listKind: ServiceInstanceList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A mocked Service Instance
          type: object
          properties:
            spec:
              description: Information about the resource
              type: object
