kind: ConfigMap
apiVersion: v1
metadata:
  name: functions
  namespace: kube-public
  labels:
    app.kubernetes.io/name: functions
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |-
    {
      "header": [],
      "body": [
        {
          "name": "Summary",
          "widget": "Panel",
          "children": [
            {
              "name": "replicas",
              "source": "spec.replicas"
            },
            {
              "name": "runtime",
              "source": "spec.runtime"
            },
            {
              "name": "runtimeImageOverride",
              "source": "spec.runtimeImageOverride"
            },
            {
              "name": "Configured",
              "source": "status.conditions[?(@.type=='ConfigurationReady')].status"
            },
            {
              "name": "Built",
              "source": "status.conditions[?(@.type=='BuildReady')].status"
            },
            {
              "name": "Running",
              "source": "status.conditions[?(@.type=='Running')].status"
            },
            {
              "name": "Runtime",
              "source": "spec.runtime"
            },
            {
              "name": "Version",
              "source": "metadata.generation"
            },
            {
              "name": "Age",
              "source": "metadata.creationTimestamp"
            }
          ]
        },
        {
          "path": "spec",
          "widget": "CodeViewer"
        }
      ]
    }
  form: |-
    [
      {
        "var": "sourceType",
        "widget": "Text",
        "enum": ["Inline", "Git Repository"],
        "dynamicValue": "$exists(spec.source.gitRepository) ? 'Git Repository' : 'Inline'"
      },
      {
        "simple": true,
        "path": "spec.runtime",
        "placeholder": "placeholders.spec.runtime",
        "enum": ["nodejs12", "nodejs14", "nodejs16", "python39"]
      },
      { "path": "spec.runtimeImageOverride" },
      {
        "path": "spec.source.gitRepository",
        "widget": "FormGroup",
        "visibility": "$sourceType = 'Git Repository'",
        "children": [
          { "path": "url" },
          { "path": "baseDir", "required": true },
          { "path": "reference", "required": true },
          {
            "var": "useAuthorization",
            "type": "boolean",
            "dynamicValue": "$exists($.spec.source.gitRepository.auth)"
          },
          {
            "widget": "FormGroup",
            "path": "auth",
            "visibility": "$useAuthorization",
            "children": [
              {
                "path": "secretName",
                "widget": "Resource",
                "resource": {
                  "kind": "Secret",
                  "version": "v1",
                  "scope": "namespace"
                }
              },
              { "path": "type" }
            ]
          },
        ]
      },
      {
        "path": "spec.scaleConfig",
        "widget": "FormGroup",
        "columns": "2",
        "children": [
          {
            "advanced": true,
            "path": "minReplicas",
            "required": false,
            "min": "1"
          },
          {
            "advanced": true,
            "path": "maxReplicas",
            "required": false,
            "min": "1"
          },
        ]
      },
      {
        "path": "spec.resourceConfiguration.function",
        "widget": "FormGroup",
        "children": [
          {
            "path": "resources.limits",
            "widget": "KeyValuePair"
          },
          {
            "path": "resources.requests",
            "widget": "KeyValuePair"
          },
        ]
      },
      {
        "path": "spec.resourceConfiguration.build",
        "widget": "FormGroup",
        "children": [
          {
            "path": "resources.limits",
            "widget": "KeyValuePair"
          },
          {
            "path": "resources.requests",
            "widget": "KeyValuePair"
          },
        ]
      },
      {
        "path": "spec.env",
        "widget": "GenericList",
        "children": [
          {
            "path": "[]",
              "children": [
                {
                  "var": "envType",
                  "widget": "Text",
                  "enum": ["Custom", "From Config Map", "From Secret"],
                  "dynamicValue": "$exists($item.valueFrom.secretKeyRef) ? 'From Secret' : ($exists($item.valueFrom.configMapKeyRef) ? 'From Config Map' : 'Custom')"
                },
                { "path": "name" },
                {
                  "path": "value",
                  "visibility": "$envType = 'Custom'"
                },
                {
                  "path": "valueFrom.secretKeyRef.name",
                  "widget": "Resource",
                  "resource": {
                    "kind": "Secret",
                    "version": "v1",
                    "scope": "namespace"
                  },
                  "provideVar": "secret",
                  "visibility": "$envType = 'From Secret'"
                },
                {
                    "path": "valueFrom.secretKeyRef.key",
                    "widget": "Text",
                    "enum": "$keys($secret.data)",
                    "visibility": "$envType = 'From Secret'"
                },
                {
                  "path": "valueFrom.configMapKeyRef.name",
                  "widget": "Resource",
                  "resource": {
                    "kind": "ConfigMap",
                    "version": "v1",
                    "scope": "namespace"
                  },
                  "provideVar": "configMap",
                  "visibility": "$envType = 'From Config Map'"
                },
                {
                    "path": "valueFrom.configMapKeyRef.key",
                    "widget": "Text",
                    "enum": "$keys($configMap.data)",
                    "visibility": "$envType = 'From Config Map'"
                }
              ]
            }
        ],
      },
      {
        "path": "spec.source.inline",
        "visibility": "$sourceType = 'Inline'",
        "children": [
          {
            "path": "source",
            "widget": "CodeEditor",
            "language": "$contains($root.spec.runtime, 'node') ? 'javascript' : 'python'",
          },
          {
            "path": "dependencies",
            "widget": "CodeEditor",
            "language": "$contains($root.spec.runtime, 'node') ? 'javascript' : 'plaintext'",
          }
        ]
      },
    ]
  general: |-
    {
      "resource": {
        "kind": "Function",
        "group": "serverless.kyma-project.io",
        "version": "v1alpha2"
      },
      "name": "Ext Functions",
      "category": "Workloads",
      "urlPath": "ext-functions",
      "scope": "namespace",
      "description": "{{[Function](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/svls-01-function/#documentation-content/)}} is a simple code snippet that you can run without provisioning or managing servers."
    }
  list: |-
    [
      {
        "name": "Runtime",
        "source": "spec.runtime = 'nodejs16' ? 'Node.js 16' : (spec.runtime = 'nodejs14' ? 'Node.js 14' : (spec.runtime = 'nodejs12' ? 'Node.js 12 - Deprecated' : (spec.runtime = 'python39' ? 'Python 3.9' : spec.runtime)))"
      },
      {
        "name": "Source Type",
        "source": "spec.source.gitRepository ? 'Git Repository' : 'Inline Editor'"
      },
      {
        "name": "Status",
        "widget": "Badge",
        "highlights": {
          "positive": ["RUNNING"],
          "negative": ["FAILED", "ERROR"],
          "informative": ["INITIALIZING"],
          "critical": ["DEPLOYING", "BUILDING", "PENDING"]
        },
        "source": "($.status = undefined or $.status.conditions = undefined or $count($.status.conditions) = 0) 
          ? 'INITIALIZING' 
          : $count($filter($.status.conditions, function($v) { $v.status = 'False' })) != 0
            ? $count($filter($.status.conditions, function($v) { $v.type = 'Running' and $v.status = 'True' })) != 0 
              ? 'ERROR'
              : 'FAILED'
            : $count($filter($.status.conditions, function($v) { $v.type = 'ConfigurationReady' and $v.status = 'True' })) != 0 
              ? $count($filter($.status.conditions, function($v) { $v.type = 'BuildReady' and $v.status = 'True' })) != 0 
                ? $count($filter($.status.conditions, function($v) { $v.type = 'Running' and $v.status = 'True' })) != 0 
                  ? 'RUNNING'
                  : $count($filter($.status.conditions, function($v) { $v.type = 'Running' and $v.status = 'Unknown' and $v.reason = 'MinReplicasNotAvailable' })) != 0 
                    ? 'PENDING'
                    : 'DEPLOYING'
                : 'BUILDING'
              : 'INITIALIZING'
        ",
        "description": "($.status = undefined or $.status.conditions = undefined or $count($.status.conditions) = 0) 
          ? null 
          : $count($filter($.status.conditions, function($v) { $v.status = 'False' })) != 0
            ? $count($filter($.status.conditions, function($v) { $v.type = 'Running' and $v.status = 'True' })) != 0 
              ? 'New revision error: ' & $filter($.status.conditions, function($v) { $v.status = 'False' })[0].message
              : 'Error: ' & $filter($.status.conditions, function($v) { $v.status = 'False' })[0].message
            : null
        "
      }
    ]
  translations: |
    en:
      spec.scaleConfig: Scale Config
      spec.scaleConfig.maxReplicas: Max Replicas
      spec.scaleConfig.minReplicas: Min Replicas
      spec.source.inline.dependencies: Dependencies
      spec.source.inline.source: Source
      spec.env: Environment Variables
      Requests: Requests
      Limits: Limits
      spec.runtime: Runtime
      spec.runtimeImageOverride: Runtime Image Override
      Status: Status
      Runtime: Runtime
      'Source Type': Source Type
      spec.runtime.nodejs12: Node.js 12 - Deprecated
      spec.runtime.nodejs14: Node.js 14
      spec.runtime.nodejs16: Node.js 16
      spec.runtime.python39: Python 3.9
      spec.resourceConfiguration.build: Build
      spec.resourceConfiguration.function: Function
      placeholders.spec.runtime: Choose Function runtime
      spec.env.name: Variable Name
      envType: Variable Type
      'Node.js Function': Node.js Function
      'Python Function': Python Function
  presets: |-
    - name: Node.js Function
      default: true
      value:
        spec:
          runtime: nodejs14
          source:
            inline:
              source: |-
                module.exports = {
                  main: async function (event, context) {
                    const message = `Hello World`
                      + ` from the Kyma Function ${context["function-name"]}`
                      + ` running on ${context.runtime}!`;
                    console.log(message);
                    return message;
                  }
                }
    - name: Python Function
      value:
        spec:
          runtime: python39
          source:
            inline:
              source: |-
                def main(event, context):
                    message = "Hello World from the Kyma Function "+context['function-name']+" running on "+context['runtime']+ "!";
                    print(message)
                    return message
