apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml
images:
  - name: busola-backend
    newName: europe-docker.pkg.dev/kyma-project/prod/busola-backend
    newTag: v0.0.1
