apiVersion: v1
kind: ConfigMap
metadata:
  name: pizzas
  namespace: pizzas
  labels:
    app.kubernetes.io/name: pizzas
    busola.io/extension: wizard
    busola.io/extension-version: '0.5'
data:
  general: |
    id: pizzas
    name: Order a pizza
    description: blah blah
    resources:
      qqq:
        kind: Qqq
        group: busola.example.com
        version: v1
      subqqq:
        kind: SubQqq
        group: busola.example.com
        version: v1
        # multiple: true # v2
  steps: |
    - name: First step
      description: this is the first step
      resource: order
      form:
        - path: spec.foo
        - path: spec.bar
        - path: $subqqq.spec.baz
    - name: Second step
      condition:
  injections: |
    - widget: Wizard
      wizard: pizzas
