kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: pizzas.busola.example.com
spec:
  group: busola.example.com
  names:
    plural: pizzas
    singular: pizza
    shortNames:
      - pz
    kind: Pizza
    listKind: PizzaList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A custom resource for making yummy pizzas
          type: object
          properties:
            spec:
              description: Information about our pizza
              type: object
              properties:
                description:
                  description: Pizza description
                  type: string
                sauce:
                  description: The name of the sauce to use on our pizza
                  type: string
                  enum:
                    - GARLIC
                    - TOMATO
                toppings:
                  description: List of toppings for our pizza
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        description: The name of the topping
                        type: string
                      price:
                        description: The price of the topping
                        type: number
                      quantity:
                        description: The quantity of the selected topping
                        type: number
                comments:
                  description: Additional comments
                  type: array
                  items:
                    type: string
                recipeSecret:
                  description: The secret containing pizza's recipe
                  type: string
                ownerReferences:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
            status:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      state:
                        type: string
  conversion:
    strategy: None
