config:
  features:
    ALLOW_PRIVATE_IPS:
      isEnabled: false
    GZIP:
      isEnabled: true
    JWT_CHECK_CONFIG:
      isEnabled: false
    KYMA_COMPANION:
      config:
        apiBaseUrl: ''
        tokenUrl: ''
