config:
  features:
    ALLOW_PRIVATE_IPS:
      isEnabled: false
    GZIP:
      isEnabled: true
    JWT_CHECK_CONFIG:
      isEnabled: false
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.kyma.cloud.sap'
        tokenUrl: 'https://kyma.accounts.ondemand.com/oauth2/token'
