name: Approval gate
on:
  workflow_call:
permissions: {}
jobs:
  select-environment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    environment: restricted
    #uncomment after gating is allowed - environment: ${{ github.event.pull_request.author_association != 'COLLABORATOR' && github.event.pull_request.author_association != 'OWNER' && 'restricted' || 'internal' }}
    steps:
      - name: Approved
        run: echo "Build approved, environment selected"
