name: Busola Web Build

on:
  push:
    branches:
      - main
      - release
    paths:
      - ".github/workflows/busola-web-build.yml"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile.web"
      - "nginx/nginx.conf"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/busola-web-build.yml"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile.web"
      - "nginx/nginx.conf"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-web-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    if: github.event.pull_request.draft == false
    with:
      name: busola-web
      dockerfile: Dockerfile.web
      context: .
      export-tags: true
      tags: latest
