name: Busola Backend Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/busola-backend-build.yml"
      - "backend/**"
      - "package.json"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/busola-backend-build.yml"
      - "backend/**"
      - "package.json"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-backend-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    if: github.event.pull_request.draft == false
    with:
      name: busola-backend
      dockerfile: Dockerfile
      context: backend
      export-tags: true
      tags: latest
