name: Busola Web Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/busola-web-build.yml"
      - "backend/**"
      - "public/**"
      - "src/**"
      - "tests/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/busola-web-build.yml"
      - "backend/**"
      - "public/**"
      - "src/**"
      - "tests/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

#test