name: Busola Web Build

on:
  workflow_call:
    inputs:
      tag:
        description: "Additional tag for built images"
        required: true
        type: string
        default: latest
  push:
    branches:
      - main
    paths:
      - ".github/workflows/busola-web-build.yml"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile.web"
      - "nginx/nginx.conf"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/busola-web-build.yml"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile.web"
      - "nginx/nginx.conf"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-web-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: busola-web
      dockerfile: Dockerfile.web
      tags: ${{ inputs.tag }}
      build-args: ${{ inputs.tag != '' && format('default_tag={0}', inputs.tag) || '' }}
