name: Busola Build

on:
  workflow_call:
    inputs:
      tag:
        description: "Additional tag for built images"
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - ".github/workflows/busola-build.yml"
      - "backend/**"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile"
      - "nginx/nginx.conf"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/busola-build.yml"
      - "kyma/**"
      - "backend/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile*"
      - "nginx/**"
      - '.github/workflows/pull-kyma-intergation-tests.yml'
      - 'resources/**'
      - 'tests/integration/**'

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-busola-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    if: github.event.pull_request.draft == false
    with:
      name: busola
      dockerfile: Dockerfile
      tags: ${{ inputs.tag != '' && inputs.tag || 'latest' }}
      build-args: ${{ inputs.tag != '' && format('tag={0}', inputs.tag) || '' }}
      platforms: |
        linux/amd64
