name: PR Description Check

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Print PR info to console
        run: |
          echo "${{ github.event.pull_request.labels }}"
          echo "${{ github.event.pull_request }}"