name: PR Description Check

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  run-desc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print PR info to console
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          {
            echo 'cleaned<<EOF'
            echo "${PR_BODY}" | tr -d '\r'
            echo EOF
          } >> "$GITHUB_OUTPUT"
  check_link_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context;
            console.log(JSON.stringify(body));
            