name: PR Description Check

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  run-desc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print PR info to console
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          {
            echo 'cleaned<<EOF'
            echo "${PR_BODY}" | tr -d '\r'
            echo EOF
          } >> "$GITHUB_OUTPUT"