name: PR Description Check

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  run-desc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print PR info to console
        run: |
          echo "${{ github.event.pull_request.head.label }}"