name: Description Check

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const prBody = context?.payload?.pull_request?.body;
            const descriptionSubtitle = "Changes proposed in this pull request";
            const nextSubtitle = "Related issue";
            const subString = prBody.substring(prBody.search(/`${descriptionSubtitle}`/) + descriptionSubtitle.length, prBody.search(/`${nextSubtitle}`/));
            console.log(subString);