name: PR Lighthouse Test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/pull-lighthouse.yml'
      - '.github/scripts/**'
      - 'resources/**'
      - 'tests/**'
      - 'nginx/**'
      - 'src/**'

jobs:
  run-lighthouse-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: gardenlinux/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge with latest main
        uses: ./.github/actions/merge
      - name: Create Single Cluster
        uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
        with:
          cluster-name: 'k3dCluster'
          args: >-
            --agents 1
            --port 80:80@loadbalancer
            --port 443:443@loadbalancer
            --wait
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 22
      - name: Run busola
        shell: bash
        run: |
          .github/scripts/setup_local_busola.sh | tee busola.log
      - name: Run lighthouse tests
        shell: bash
        run: |
          k3d kubeconfig get k3dCluster > tests/lighthouse/fixtures/kubeconfig.yaml
          cd tests/lighthouse
          npm ci && npx playwright install --with-deps && npm run "test"
      - name: Upload Busola logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: busola-logs-${{ github.job }}
          path: |
            busola.log
          retention-days: 90
