name: PR Integration Namespace Tests

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/pull-integration-namespace-k3d.yml'
      - '.github/scripts/**'
      - "backend/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "Dockerfile*"
      - "nginx/**"
      - 'resources/**'
      - 'tests/integration/**'

jobs:
  run-namespace-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: gardenlinux/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge with latest main
        uses: ./.github/actions/merge
      - name: Create Single Cluster
        uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
        with:
          cluster-name: 'k3dCluster'
          args: >-
            --agents 1
            --port 80:80@loadbalancer
            --port 443:443@loadbalancer
            --wait
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 22
      - name: Setup Busola
        shell: bash
        run: |
          .github/scripts/setup_local_busola.sh | tee busola.log
      - name: Run tests
        shell: bash
        run: |
          export CYPRESS_DOMAIN=http://localhost:3001
          k3d kubeconfig get k3dCluster > tests/integration/fixtures/kubeconfig.yaml          
          cd tests/integration
          npm ci && npm run "test:namespace"
      - name: Uploads artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: cypress-${{ github.job }}
          path: tests/integration/cypress/
          retention-days: 90
      - name: Upload Busola logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: busola-logs-${{ github.job }}
          path: |
            busola.log
          retention-days: 90
